baseURL: "https://codenanshu.in"
languageCode: "en-us"
title: "CodeNanshu"
pygmentsstyle: 'dracula'
metaDataFormat: yaml

# Theme settings
# theme: novela
module:
  imports:
    - path: "github.com/forestryio/hugo-theme-novela"
paginate: 6
social:
  twitter: "https://twitter.com/aianshume"
  github: "https://github.com/aianshume"
  instagram: "https://instagram.com/aianshu_2308"
  linkedin: "#"
  dribbble: "#"
  youtube: "https://youtube.com/@CodeNanshu"
taxonomies:
  author: authors
